'use client';
import React from 'react';

const AIRecommendedAssetsTable = () => {
  const assets = [
    { icon: "fab fa-apple", name: "Apple Inc.", ticker: "AAPL", price: "$189.25", change: "+7.2%", changeType: "positive", confidence: 92, predictedPrice: "$202.92", action: "Buy", actionClass: "buy" },
    { icon: "fab fa-google", name: "Alphabet Inc.", ticker: "GOOGL", price: "$138.42", change: "+5.8%", changeType: "positive", confidence: 85, predictedPrice: "$146.37", action: "Buy", actionClass: "buy" },
    { icon: "fab fa-microsoft", name: "Microsoft", ticker: "MSFT", price: "$338.11", change: "-2.3%", changeType: "negative", confidence: 78, predictedPrice: "$330.24", action: "Sell", actionClass: "sell" },
    { icon: "fab fa-bitcoin", name: "Bitcoin", ticker: "BTC", price: "$42,876", change: "+12.5%", changeType: "positive", confidence: 88, predictedPrice: "$48,235", action: "Buy", actionClass: "buy" },
  ];

  return (
    <div className="dashboard-card ai-assets-table-card">
      <div className="dashboard-card-header">
        <h3 className="dashboard-card-title">AI Recommended Assets</h3>
        <div className="card-header-action">
          <button>
            <i className="fas fa-sync-alt"></i> Refresh Predictions
          </button>
        </div>
      </div>
      <div className="table-wrapper">
        <table className="predictions-table">
          <thead>
            <tr>
              <th>Asset</th>
              <th>Current Price</th>
              <th>Predicted Change</th>
              <th>AI Confidence</th>
              <th>Predicted Price</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {assets.map((asset, index) => (
              <tr key={index}>
                <td>
                  <div className="asset-identity-cell">
                    <div className="asset-icon-container">
                      <i className={asset.icon}></i>
                    </div>
                    <div>
                      <div className="asset-name-full">{asset.name}</div>
                      <div className="asset-ticker-symbol">{asset.ticker}</div>
                    </div>
                  </div>
                </td>
                <td>{asset.price}</td>
                <td className={`asset-price-change ${asset.changeType}`}>{asset.change}</td>
                <td className="ai-confidence-rating">
                  <div className="confidence-bar-bg">
                    <div 
                        className={`confidence-bar-fill ${asset.confidence > 80 ? 'green' : 'yellow'}`} 
                        style={{ width: `${asset.confidence}%` }}
                    ></div>
                  </div>
                  <div className={`confidence-percentage ${asset.confidence > 80 ? 'green' : 'yellow'}`}>
                    {asset.confidence}%
                  </div>
                </td>
                <td className="asset-predicted-price">{asset.predictedPrice}</td>
                <td>
                  <button className={`asset-action-button ${asset.actionClass}`}>{asset.action}</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="table-footer-disclaimer">
        <i className="fas fa-exclamation-triangle"></i>
        Past performance is not indicative of future results. Asset recommendations are generated by AI algorithms based on historical data and current market conditions.
      </div>
    </div>
  );
};

export default AIRecommendedAssetsTable;